// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfIoaFEghJXjnKhVsdlbg3SxPuzBZHZME',
    appId: '1:519399230930:web:a40f1f0e787cf209c08c0b',
    messagingSenderId: '519399230930',
    projectId: 'barangay-profiling-system',
    authDomain: 'barangay-profiling-system.firebaseapp.com',
    storageBucket: 'barangay-profiling-system.firebasestorage.app',
    measurementId: 'G-3PFJV0MK73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTUZ621eG-tOokS84nyL0KmKRxl_2lOXM',
    appId: '1:519399230930:android:850ec57eb5e8b8fbc08c0b',
    messagingSenderId: '519399230930',
    projectId: 'barangay-profiling-system',
    storageBucket: 'barangay-profiling-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxkjo546LmTrEifCKZM5fy_e6XL9qORos',
    appId: '1:519399230930:ios:dca265820b0c2f6cc08c0b',
    messagingSenderId: '519399230930',
    projectId: 'barangay-profiling-system',
    storageBucket: 'barangay-profiling-system.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxkjo546LmTrEifCKZM5fy_e6XL9qORos',
    appId: '1:519399230930:ios:dca265820b0c2f6cc08c0b',
    messagingSenderId: '519399230930',
    projectId: 'barangay-profiling-system',
    storageBucket: 'barangay-profiling-system.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfIoaFEghJXjnKhVsdlbg3SxPuzBZHZME',
    appId: '1:519399230930:web:e196989e66cffd2cc08c0b',
    messagingSenderId: '519399230930',
    projectId: 'barangay-profiling-system',
    authDomain: 'barangay-profiling-system.firebaseapp.com',
    storageBucket: 'barangay-profiling-system.firebasestorage.app',
    measurementId: 'G-WNJZBDNR1Q',
  );
}
