name: Flutter Web Build

on:
  push:
    branches:
      - main  # Adjust branch name if necessary

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29'  # Change to your Flutter version
          channel: 'stable'

      - name: Verify Flutter Installation
        run: flutter --version  # Debug step to check Flutter installation

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Web
        run: flutter build web
